filter_secrets: false
language: python
python:
  - "3.5"

install:
  - pip3 install HookTest>=1.0.0

script:
  - hooktest ./ --scheme tei --workers 3 --verbose 10 --console table --countword --allowfailure
